// micro-frontends/iframes/employees/src/components/Panel.tsx
import React from "react";
import classes from './Panel.module.css';

export interface PanelProps {
  title?: string;
  icon?: string;
  iconHelp?: string;
  iconBadge?: string;
}

const Panel: React.FC<PanelProps> = (props) => {
  const { children, title, icon, iconHelp, iconBadge } = props;

  return (
    <div className={classes.panel}>
      <div className={classes.panelHeader}>
        <h1 className={classes.panelTitle}>{title}</h1>
        <span className={[classes.panelIcon, classes[`panelIcon${icon}`]].join(' ')} title={iconHelp || icon} />
        {!!iconBadge && <span className={classes.panelIconBadge}>{iconBadge}</span>}
      </div>
      <div className={classes.panelBody}>
        {children}
      </div>
    </div>
  )
}

export default Panel;

// micro-frontends/single-spa/packages/settings-angular/src/app/panel/panel.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: 'app-panel',
  templateUrl: './panel.component.html',
  styleUrls: ['./panel.component.css'],
})
export class PanelComponent {
  @Input()
  panelTitle: string = '';

  @Input()
  icon?: string;

  @Input()
  iconHelp?: string;

  @Input()
  iconBadge?: string;
}

<div class="panelHeader">
  <h1 class="panelTitle">{{ panelTitle }}</h1>
  <span class="panelIcon" [ngClass]="'panelIcon' + icon" [title]="iconHelp || icon"></span>
  <span class="panelIconBadge" *ngIf="iconBadge">{{ iconBadge }}</span>

</div>
<div class="panelBody">
  <ng-content></ng-content>
</div>
